export const GET_BOOKS_LIST_REQUEST = "GET_BOOKS_LIST_REQUEST"
export const GET_BOOKS_LIST_SUCCESS = "GET_BOOKS_LIST_SUCCESS"
export const GET_BOOKS_LIST_ERROR = "GET_BOOKS_LIST_ERROR"

export const GET_SINGLE_BOOK_REQUEST = "GET_SINGLE_BOOK_REQUEST"
export const GET_SINGLE_BOOK_SUCCESS = "GET_SINGLE_BOOK_SUCCESS"
export const GET_SINGLE_BOOK_ERROR = "GET_SINGLE_BOOK_ERROR"